name: Build EXE
on: [push]

jobs:
build:
runs-on: windows-latest
steps:
# 拉取仓库代码（最新版v4）
- uses: actions/checkout@v4

# 配置Python环境（最新版v5，支持Python 3.8+）
- name: Set up Python
uses: actions/setup-python@v5
with:
python-version: '3.10'  # 可调整为你的Python版本（如3.9、3.11）

# 安装依赖（清华镜像加速，解决国内下载慢）- name: Install dependencies
run: |
pip install -i https://pypi.tuna.tsinghua.edu.cn/simple pyinstaller pyqt5

# 打包EXE（保持与之前一致，确保图片文件名正确）
- name: Build EXE
run: |
pyinstaller --onefile --windowed --name ChessAssistant --add-data "chinese_chess_board.png;." chess_assistant.py

# 上传打包结果（最新版v4，解决旧版失败问题）
- uses: actions/upload-artifact@v4
with:
name: chess-assistant  #  artifacts名称（可自定义）
path: dist/  # PyInstaller默认输出目录（无需修改）
