name: Build EXE
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      # 1. 拉取仓库代码
      - uses: actions/checkout@v4

      # 2. 配置Python环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. 安装依赖（添加opencv-python-headless）
      - name: Install dependencies
        run: |
          pip install -i https://pypi.tuna.tsinghua.edu.cn/simple pyinstaller pyqt5 opencv-python-headless numpy pywin32

      # 4. 打包EXE（添加--hidden-import参数）
      - name: Build EXE
        run: |
          pyinstaller --onefile --windowed `
            --name ChessAssistant `
            --hidden-import cv2 `
            --hidden-import numpy `
            --add-data "chinese_chess_board.png;." `
            chess_assistant.py
          
          # 验证打包结果
          dir dist

      # 5. 上传打包结果
      - uses: actions/upload-artifact@v4
        with:
          name: chess-assistant
          path: dist/
