name: Build EXE
on: [push]

jobs:
  build:  # 一级任务，缩进2个空格（相对于jobs:）
    runs-on: windows-latest  # 任务属性，缩进2个空格
    steps:  # 任务步骤列表，缩进2个空格
      # 1. 拉取仓库代码（最新版v4）
      - uses: actions/checkout@v4  # 步骤1：用-开头，无额外缩进（相对于steps:）

      # 2. 配置Python环境（最新版v5）
      - name: Set up Python  # 步骤2：名称，-开头
        uses: actions/setup-python@v5  # 步骤属性：缩进2个空格（相对于- name:）
        with:  # 步骤参数：缩进2个空格（相对于uses:）
          python-version: '3.10'  # 参数值：缩进2个空格（相对于with:）

      # 3. 安装依赖（清华镜像加速）
      - name: Install dependencies  # 步骤3：名称，-开头
        run: |  # 步骤命令：缩进2个空格（相对于- name:）
          pip install -i https://pypi.tuna.tsinghua.edu.cn/simple pyinstaller pyqt5  # 命令行：缩进2个空格（相对于run: |）

      # 4. 打包EXE（生成可执行文件）
      - name: Build EXE  # 步骤4：名称，-开头
        run: |  # 步骤命令：缩进2个空格
          pyinstaller --onefile --windowed --name ChessAssistant --add-data "chinese_chess_board.png;." chess_assistant.py  # 命令行：缩进2个空格

      # 5. 上传打包结果（最新版v4）
      - uses: actions/upload-artifact@v4  # 步骤5：用-开头
        with:  # 步骤参数：缩进2个空格
          name: chess-assistant  #  artifacts名称：缩进2个空格
          path: dist/  # 输出目录：缩进2个空格
