name: Build EXE

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          pip install pyinstaller pyqt5
          
      - name: Build EXE
        run: |
          pyinstaller --onefile --windowed --name ChessAssistant --add-data "chinese_chess_board.png;." chess_assistant.py
          
      - uses: actions/upload-artifact@v4 
        with:
        name: chess-assistant
        path: dist/
